version: '3.8'
volumes:
  postgres_data:

services:
  web:
    build: 
      context: .
      dockerfile: compose/Dockerfile
      args:
        DEBUG_ARG: true
    container_name: appetit_web
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src
    ports:
      - '8088:8080'
    env_file:
      - .env

  postgres:
    image: postgres:17.5 
    container_name: appetit_psql
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      