"""rename mod option column

Revision ID: 0028b4b4b34e
Revises: e54dfdba851f
Create Date: 2025-08-25 01:29:24.181241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0028b4b4b34e'
down_revision: Union[str, Sequence[str], None] = 'e54dfdba851f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        "modifier_option",
        "food_modifier_option_id",
        new_column_name="modifier_category_id",
        schema="menu"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "modifier_option",
        "modifier_category_id",
        new_column_name="food_modifier_option_id",
        schema="menu"
    )
    # ### end Alembic commands ###
