"""extend order model

Revision ID: 067f182cf167
Revises: f75705c86eaa
Create Date: 2025-08-28 22:23:53.371022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067f182cf167'
down_revision: Union[str, Sequence[str], None] = 'f75705c86eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True), schema='orders')
    op.alter_column('orders', 'total_sum',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_sum',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               schema='orders')
    op.drop_column('orders', 'address', schema='orders')
    # ### end Alembic commands ###