"""restaurant model

Revision ID: 1e3c0ced9cec
Revises: dde16e152775
Create Date: 2025-08-28 10:10:41.284281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3c0ced9cec'
down_revision: Union[str, Sequence[str], None] = 'dde16e152775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'menu', 'food', ['food_id'], ['id'], source_schema='menu', referent_schema='menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu', schema='menu', type_='foreignkey')
    # ### end Alembic commands ###