"""food.image_path

Revision ID: 509904d5b830
Revises: 80de49c0925d
Create Date: 2025-08-28 21:22:36.721481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509904d5b830'
down_revision: Union[str, Sequence[str], None] = '80de49c0925d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('image_path', sa.String(), nullable=True), schema='menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'image_path', schema='menu')
    # ### end Alembic commands ###