"""divide OrderFoodFoodSize into OrderFood and OrderFoodSize

Revision ID: 5ac7d7ea4092
Revises: 067f182cf167
Create Date: 2025-08-28 22:36:32.614927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac7d7ea4092'
down_revision: Union[str, Sequence[str], None] = '067f182cf167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_food',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['menu.food.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_table('orders_food_size',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('food_size_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_size_id'], ['menu.food_size.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.drop_table('orders_food_food_size', schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_food_food_size',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('food_size_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['menu.food.id'], name=op.f('orders_food_food_size_food_id_fkey')),
    sa.ForeignKeyConstraint(['food_size_id'], ['menu.food_size.id'], name=op.f('orders_food_food_size_food_size_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], name=op.f('orders_food_food_size_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_food_food_size_pkey')),
    schema='orders'
    )
    op.drop_table('orders_food_size', schema='orders')
    op.drop_table('orders_food', schema='orders')
    # ### end Alembic commands ###