"""empty message

Revision ID: 638bfa85e11e
Revises: 5ac7d7ea4092
Create Date: 2025-08-28 23:39:27.735902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638bfa85e11e'
down_revision: Union[str, Sequence[str], None] = '5ac7d7ea4092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False), schema='orders')
    op.create_foreign_key(None, 'orders', 'user', ['user_id'], ['id'], source_schema='orders', referent_schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', schema='orders', type_='foreignkey')
    op.drop_column('orders', 'user_id', schema='orders')
    # ### end Alembic commands ###