"""restaurant lat, lon

Revision ID: 80de49c0925d
Revises: 662da2f6686a
Create Date: 2025-08-28 16:44:57.450885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80de49c0925d'
down_revision: Union[str, Sequence[str], None] = '662da2f6686a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('lat', sa.Float(), nullable=False), schema='restaurant')
    op.add_column('restaurant', sa.Column('lon', sa.Float(), nullable=False), schema='restaurant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'lon', schema='restaurant')
    op.drop_column('restaurant', 'lat', schema='restaurant')
    # ### end Alembic commands ###