"""menu.food_id

Revision ID: 990963fe807c
Revises: b5e828f23fca
Create Date: 2025-08-27 19:15:56.737114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990963fe807c'
down_revision: Union[str, Sequence[str], None] = 'b5e828f23fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menu", "name", schema="menu")
    op.add_column("menu", sa.Column("food_id", sa.Integer(), nullable=False),
                                    schema="menu")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menu", "food_id", schema="menu")
    op.add_column("menu", sa.Column("name", sa.String(), nullable=False),
                  schema="menu")
    # ### end Alembic commands ###