"""food.description

Revision ID: b5e828f23fca
Revises: 0028b4b4b34e
Create Date: 2025-08-26 08:35:17.809294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e828f23fca'
down_revision: Union[str, Sequence[str], None] = '0028b4b4b34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "food", sa.Column("description", sa.String(), nullable=False),
        schema="menu"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "food", "description",
        schema = "menu"
    )
    # ### end Alembic commands ###