"""empty message

Revision ID: b79758753011
Revises: 638bfa85e11e
Create Date: 2025-08-29 01:10:13.091604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79758753011'
down_revision: Union[str, Sequence[str], None] = '638bfa85e11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('restaurant_id', sa.Integer(), nullable=False), schema='orders')
    op.create_foreign_key(None, 'orders', 'restaurant', ['restaurant_id'], ['id'], source_schema='orders', referent_schema='restaurant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', schema='orders', type_='foreignkey')
    op.drop_column('orders', 'restaurant_id', schema='orders')
    # ### end Alembic commands ###