"""drop field menu.priority_name

Revision ID: dde16e152775
Revises: 990963fe807c
Create Date: 2025-08-27 19:23:18.389147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde16e152775'
down_revision: Union[str, Sequence[str], None] = '990963fe807c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menu", "priority_name", schema="menu")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("menu", sa.Column("priority_name", sa.String(), nullable=True),
                  schema="menu")
    # ### end Alembic commands ###