"""food

Revision ID: e54dfdba851f
Revises: f5cc9eafce21
Create Date: 2025-08-24 11:38:13.607248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54dfdba851f'
down_revision: Union[str, Sequence[str], None] = 'f5cc9eafce21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_type',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    op.create_table('menu',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('priority_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    op.create_table('modifier_category',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    op.create_table('food',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['menu.food_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    op.create_table('modifier_option',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('food_modifier_option_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_modifier_option_id'], ['menu.modifier_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    op.create_table('food_modifier_options',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('modifier_option_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['menu.food.id'], ),
    sa.ForeignKeyConstraint(['modifier_option_id'], ['menu.modifier_option.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    op.create_table('food_size',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['menu.food.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_size', schema='menu')
    op.drop_table('food_modifier_options', schema='menu')
    op.drop_table('modifier_option', schema='menu')
    op.drop_table('food', schema='menu')
    op.drop_table('modifier_category', schema='menu')
    op.drop_table('menu', schema='menu')
    op.drop_table('food_type', schema='menu')
    # ### end Alembic commands ###