"""empty message

Revision ID: f75705c86eaa
Revises: 509904d5b830
Create Date: 2025-08-28 22:06:21.808364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75705c86eaa'
down_revision: Union[str, Sequence[str], None] = '509904d5b830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_table('orders',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('total_sum', sa.Float(), nullable=False),
    sa.Column('is_payed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['orders.order_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_table('orders_modifier_option',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('modifier_option_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modifier_option_id'], ['menu.modifier_option.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_table('orders_food_food_size',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('food_size_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['menu.food.id'], ),
    sa.ForeignKeyConstraint(['food_size_id'], ['menu.food_size.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_food_food_size', schema='orders')
    op.drop_table('orders_modifier_option', schema='orders')
    op.drop_table('orders', schema='orders')
    op.drop_table('order_status', schema='orders')
    # ### end Alembic commands ###